### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by nickbearman** [jasoncpit/RGS_presentation#1]
Hi Jason, just curious how you put together your presentation? I couldn't work it out from the source. I experiment with Quarto for mine (https://github.com/nickbearman/2022-09-01-rgs-locus-charter-ethics) although I think it needs a bit more work!
Thanks,
Nick.

**Comment by jasoncpit** [comment]
Hi Nick,

I exported the presentation to html, and published it through GitHub io. Here is a useful link I found..

Best

Jason

https://www.freecodecamp.org/news/publish-your-website-netlify-github/amp/


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Nick Bearman ***@***.***>
Sent: Friday, September 2, 2022 5:42:38 PM
To: jasoncpit/RGS_presentation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jasoncpit/RGS_presentation] Presentation (Issue #1)


⚠ Caution: External sender


Hi Jason, just curious how you put together your presentation? I couldn't work it out from the source. I experiment with Quarto for mine (https://github.com/nickbearman/2022-09-01-rgs-locus-charter-ethics) although I think it needs a bit more work!
Thanks,
Nick.

**Comment by nickbearman** [comment]
Thanks Jason - good to know! There are so many different options....
